server:
  port: 9961
spring:
  application:
    name: my-blog-user
  #这里是换数据源为druid，且配置连接数据库的信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/myblog?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: wc415576379
  redis:
    host: 127.0.0.1
    port: 6379
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml #mapper映射文件
  type-aliases-package: com.dynasty.blog.user.entity
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
logging:
  level:
    com.dynasty.blog.user: debug





